baseURL = "/"
languageCode = "en-us"
title = "Cartgasm"
theme = "cartgasm"
publishDir = "docs"
uglyURLs = false
sectionPagesMenu = "main"
enableEmoji = true

# Copyright
copyright = "(c) 2015 yourname."

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  subtitle = "Hugo is Absurdly Fast!"
